In [14]:
import thesis_helper
functions = thesis_helper.Thesis_Helper()
from tqdm import tqdm
tqdm.pandas()

In [15]:
df = functions.folder_reader('/Users/ivowings/Sync/Thesis/Datasources/Preprocessed/Combined/Taxonomy/Normal')

In [16]:
df = df['concatenated'].str.split('|',expand=True)
df

,0,1,2
0,editors to meet site,goals search,and select photos for
1,working on a company,s strategic,and core product demand
2,coordinating communication,across task areas,and with the
3,,skills bachelor,s
4,interacting with individuals from,diverse,ethnic and socio economic
...,...,...,...
5404035,systems related software and our,practice management,software plans appointments meetings and
5404036,needs interacts with,all it management and,staff located in
5404037,compliance with generally accepted,accounting principles,gaap
5404038,team for efficient,marketing strategy and,marketing material design
5404039,must,haves superb writing,skills from 140

In [17]:
df = df.rename(columns={0:'left_context', 1:'candidate_skill', 2:'right_context'})

In [18]:
df['candidate_skill'] = df['candidate_skill'].str.strip()
df

,left_context,candidate_skill,right_context
0,editors to meet site,goals search,and select photos for
1,working on a company,s strategic,and core product demand
2,coordinating communication,across task areas,and with the
3,,skills bachelor,s
4,interacting with individuals from,diverse,ethnic and socio economic
...,...,...,...
5404035,systems related software and our,practice management,software plans appointments meetings and
5404036,needs interacts with,all it management and,staff located in
5404037,compliance with generally accepted,accounting principles,gaap
5404038,team for efficient,marketing strategy and,marketing material design
5404039,must,haves superb writing,skills from 140

In [19]:
import spacy
import csv
nlp = spacy.load("en_core_web_sm")

In [20]:
df['length'] = df['candidate_skill'].progress_apply(nlp)
df['length'] = df['length'].progress_apply(len)
df

100%|██████████| 5404040/5404040 [9:23:25<00:00, 159.86it/s]
100%|██████████| 5404040/5404040 [00:05<00:00, 928643.65it/s]

,left_context,candidate_skill,right_context,length
0,editors to meet site,goals search,and select photos for,2
1,working on a company,s strategic,and core product demand,2
2,coordinating communication,across task areas,and with the,3
3,,skills bachelor,s,2
4,interacting with individuals from,diverse,ethnic and socio economic,1
...,...,...,...,...
5404035,systems related software and our,practice management,software plans appointments meetings and,2
5404036,needs interacts with,all it management and,staff located in,4
5404037,compliance with generally accepted,accounting principles,gaap,2
5404038,team for efficient,marketing strategy and,marketing material design,3
5404039,must,haves superb writing,skills from 140,3

In [22]:
df = df.sort_values(by='length')

In [23]:
import numpy as np
import csv
partitions = 5
dfs = np.array_split(df, partitions)

for x in range(0,partitions):
    dfs[x].to_csv("/Users/ivowings/Sync/Thesis/Datasources/Preprocessed/Combined/Taxonomy/Sorted/context_{}.csv".format(x),
          quoting=csv.QUOTE_NONNUMERIC,
          index=False)

In [26]:
dfs[0]

,left_context,candidate_skill,right_context,length
2654919,an agile scrum,team,to deliver customer,1
3800602,,responsibilities,define,1
524474,and professional communication,skills,written and,1
1003825,and share daily content original,text,images video or html that,1
524476,experience with javascript,html5,css3 and jquery,1
...,...,...,...,...
3398483,databases such as mongodb,cassandra redis,etc experience with drcs,2
1937498,s modify blends using,low cost,resin review and manage,2
3398485,our engineering,team is,responsible for building transifex as,2
1937517,during,arbitration hearings,and,2
3400349,nature and therefore,requires diplomacy,and discretion and,2